controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_hand_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint6
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: zero_pose
  - group: hand_group
    pose: hand_closed